### ISSUE TITLE
Is this usable yet?

### ISSUE THREAD

**Issue by JackMK0001** [RedYetiDev/membean#1]
I have to achieve 45 minutes by tomorrow, and I'm wondering if this is ready to be utilized yet?

**Comment by avivkeller** [comment]
Hey there, while unstable, this package is indeed usable. It's currently at a state where everything works the intended way, but I haven't documented a README yet.

I'm planning to make a README in the coming week, and from there, usage instructions will be much simpler.

**Comment by JackMK0001** [comment]
Can you provide some simple instructions for me just to be able to use it for today?

**Comment by avivkeller** [comment]
This framework is meant to be extensible and allow users to build their own systems. There isn't a one-size-fits-all answer. If you just want a robot to do your membean for you, then a layout would look like this:
```js
// Import the MemBeanTrainingSession class
import MemBeanTrainingSession from './MemBeanTrainingSession.js';

// Define your Membean session ID and authentication token
const sessionId = 'YOUR_SESSION_ID';
const authToken = 'YOUR_AUTH_TOKEN';

// Create a new instance of MemBeanTrainingSession
const session = new MemBeanTrainingSession(sessionId, authToken);
const sleep = ms => new Promise(r => setTimeout(r, ms))

// Listen for events emitted by the session
session.on('new_word', async data => {
    console.log('New Word:', data.word);
    await sleep(120 * 1000); // 2 minutes
    session.advance(data.nav["Next"]);
});

session.on('restudy', async data => {
    console.log('Restudy:', data.word);
    await sleep(120 * 1000); // 2 minutes
    session.advance(data.nav["Next"]);
});

session.on('quiz', async data => {
    console.log('Quiz');
    await sleep(20 * 1000); // 20 seconds
    session.advance(data.answer.pass);
});

session.on('spelltest', async data => {
    console.log('Spell Test');
    await sleep(20 * 1000); // 20 seconds
    session.advance(data.answer.pass);
});

session.on('take_a_break', () => {
    console.log('Take a Break');
});

(async () => {
    try {
        await session.parseUserState();
    } catch (error) {
        console.error('Error:', error);
    }
})();
```

Keep in mind that this project isn't meant to just be a robot for cheating, its meant to extend the membean API. Also, I did not test the code above, as I literally just wrote it up, so it may not work as intended.

**Comment by JackMK0001** [comment]
so the chances of it getting detected and me getting dubious minutes are high?

**Comment by avivkeller** [comment]
No, not quite. If it works, then they are quite low, if it doesn't work, then nothing will happen.

**Comment by JackMK0001** [comment]
How do I get it to work? I really need something to just do minutes for me

**Comment by avivkeller** [comment]
I've given you the code that I believe may work, but other than that, there is not much I can do. I'm sorry for the trouble, but this library may not suit your needs.

**Comment by avivkeller** [comment]
If you need any more help, feel free to reach out to me at <redyetidev@gmail.com>.
